name: Simple GitHub Action

on:
  push:

jobs:
  build1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4

      - name: Execute Python file
        run: python hello.py